FROM marcelmittelstaedt/airflow:latest

ADD ./kaggle.json /home/airflow/.kaggle/kaggle.json

ADD ./src /home/airflow/airflow/dags/

# Expose Airflow Web Service Port
EXPOSE 8080

# Start startup Script
ENTRYPOINT ["/startup.sh"]
