download_path = '/home/airflow'
download_folder = 'hubway_data'
remote_path_raw = '/user/hadoop/hubway/raw/'
remote_path_final = '/user/hadoop/hubway/final/'
remote_path_hivesql = '/user/hadoop/hubway/sql/'
hdfs_conn_id='hdfs'